In [1]:
import pandas as pd
import sqlite3

In [3]:
df = pd.read_csv("cleaned_sales_data.csv")

In [4]:
conn = sqlite3.connect("walmart_sales.db")

In [5]:
df.to_sql(
    name="sales",
    con=conn,
    if_exists="replace",
    index=False
)

6435

In [6]:
pd.read_sql("""
SELECT COUNT(*) AS total_records
FROM sales;
""", conn)

   total_records
0           6435

In [14]:
pd.read_sql("""
SELECT ROUND(SUM(Weekly_Sales), 2) AS total_revenue
FROM sales;
""", conn)

   total_revenue
0   6.737219e+09

In [16]:
pd.read_sql("""
SELECT ROUND(AVG(Weekly_Sales), 2) AS average_weekly_sales
FROM sales;
""", conn)

   average_weekly_sales
0            1046964.88

In [17]:
pd.read_sql("""
SELECT
    Store,
    ROUND(SUM(Weekly_Sales),2) AS revenue
FROM sales
GROUP BY Store
ORDER BY revenue DESC
LIMIT 10;
""", conn)

   Store       revenue
0     20  3.013978e+08
1      4  2.995440e+08
2     14  2.889999e+08
3     13  2.865177e+08
4      2  2.753824e+08
5     10  2.716177e+08
6     27  2.538559e+08
7      6  2.237561e+08
8      1  2.224028e+08
9     39  2.074455e+08

In [18]:
pd.read_sql("""
SELECT
    Holiday_Flag,
    ROUND(SUM(Weekly_Sales),2) AS revenue,
    COUNT(*) AS total_weeks
FROM sales
GROUP BY Holiday_Flag;
""", conn)

   Holiday_Flag       revenue  total_weeks
0             0  6.231919e+09         5985
1             1  5.052996e+08          450

In [19]:
pd.read_sql("""
SELECT
    Store,
    ROUND(AVG(Weekly_Sales),2) AS avg_sales
FROM sales
GROUP BY Store
ORDER BY avg_sales DESC;
""", conn)

    Store   avg_sales
0      20  2107676.87
1       4  2094712.96
2      14  2020978.40
3      13  2003620.31
4       2  1925751.34
5      10  1899424.57
6      27  1775216.20
7       6  1564728.19
8       1  1555264.40
9      39  1450668.13
10     19  1444999.04
11     31  1395901.44
12     23  1389864.46
13     24  1356755.39
14     11  1356383.12
15     28  1323522.24
16     41  1268125.42
17     32  1166568.15
18     18  1084718.42
19     22  1028501.04
20     12  1009001.61
21     26  1002911.84
22     34   966781.56
23     40   964128.04
24     35   919724.98
25      8   908749.52
26     17   893581.39
27     45   785981.41
28     21   756069.08
29     25   706721.53
30     43   633324.72
31     15   623312.47
32      7   570617.31
33     42   556403.86
34      9   543980.55
35     29   539451.43
36     16   519247.73
37     37   518900.28
38     30   438579.62
39      3   402704.44
40     38   385731.65
41     36   373511.99
42      5   318011.81
43     44   302748.87
44     33   259861.69

In [20]:
pd.read_sql("""
SELECT
    Store,
    ROUND(SUM(Weekly_Sales),2) AS revenue
FROM sales
GROUP BY Store
HAVING SUM(Weekly_Sales) >
(
    SELECT AVG(Weekly_Sales) * COUNT(DISTINCT Store)
    FROM sales
)
ORDER BY revenue DESC;
""", conn)

    Store       revenue
0      20  3.013978e+08
1       4  2.995440e+08
2      14  2.889999e+08
3      13  2.865177e+08
4       2  2.753824e+08
5      10  2.716177e+08
6      27  2.538559e+08
7       6  2.237561e+08
8       1  2.224028e+08
9      39  2.074455e+08
10     19  2.066349e+08
11     31  1.996139e+08
12     23  1.987506e+08
13     24  1.940160e+08
14     11  1.939628e+08
15     28  1.892637e+08
16     41  1.813419e+08
17     32  1.668192e+08
18     18  1.551147e+08
19     22  1.470756e+08
20     12  1.442872e+08
21     26  1.434164e+08
22     34  1.382498e+08
23     40  1.378703e+08
24     35  1.315207e+08
25      8  1.299512e+08
26     17  1.277821e+08
27     45  1.123953e+08
28     21  1.081179e+08
29     25  1.010612e+08
30     43  9.056544e+07
31     15  8.913368e+07
32      7  8.159828e+07
33     42  7.956575e+07
34      9  7.778922e+07
35     29  7.714155e+07
36     16  7.425243e+07
37     37  7.420274e+07
38     30  6.271689e+07
39      3  5.758674e+07
40     38  5.515963e+07
41     36  5.341221e+07